/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 22 16:48:51 CET 2017
 */

package website.automate.manager.api.client.model;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.junit.Test;

public class BoxTest  {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Box box0 = new Box();
      box0.setOs("d");
      String string0 = box0.getOs();
      assertEquals("d", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Box box0 = new Box();
      box0.setBrowser("d");
      String string0 = box0.getBrowser();
      assertEquals("d", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Box box0 = new Box();
      box0.setBrowser("");
      String string0 = box0.getBrowser();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Box box0 = new Box();
      String string0 = box0.getBrowser();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Box box0 = new Box();
      box0.setOs("");
      String string0 = box0.getOs();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Box box0 = new Box();
      String string0 = box0.getOs();
      assertNull(string0);
  }
}
