/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 23 09:05:42 CET 2017
 */

package website.automate.manager.api.client.model;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;

import java.util.ArrayList;

import org.junit.Test;

 
public class ReportTest   {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Report report0 = new Report();
      ArrayList<Scenario> arrayList0 = new ArrayList<Scenario>();
      Scenario scenario0 = new Scenario();
      arrayList0.add(scenario0);
      report0.setScenarios(arrayList0);
      ArrayList<Scenario> arrayList1 = report0.getScenarios();
      assertSame(arrayList1, arrayList0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Report report0 = new Report();
      ArrayList<Scenario> arrayList0 = report0.getScenarios();
      assertNull(arrayList0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Report report0 = new Report();
      ArrayList<Scenario> arrayList0 = new ArrayList<Scenario>();
      report0.setScenarios(arrayList0);
      ArrayList<Scenario> arrayList1 = report0.getScenarios();
      assertEquals(0, arrayList1.size());
  }
}
