/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 23 09:06:43 CET 2017
 */

package website.automate.manager.api.client.model;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import java.util.ArrayList;

import org.junit.Test;

public class ScenarioTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Scenario scenario0 = new Scenario();
      ArrayList<Step> arrayList0 = new ArrayList<Step>();
      scenario0.steps = arrayList0;
      Step step0 = new Step();
      arrayList0.add(step0);
      ArrayList<Step> arrayList1 = scenario0.getSteps();
      assertEquals(1, arrayList1.size());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Scenario scenario0 = new Scenario();
      scenario0.numStepPasses = 1;
      int int0 = scenario0.getNumStepPasses();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Scenario scenario0 = new Scenario();
      scenario0.setNumStepPasses((-1));
      int int0 = scenario0.getNumStepPasses();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Scenario scenario0 = new Scenario();
      scenario0.setNumStepFailures(1);
      int int0 = scenario0.getNumStepFailures();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Scenario scenario0 = new Scenario();
      scenario0.numStepFailures = (-1);
      int int0 = scenario0.getNumStepFailures();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Scenario scenario0 = new Scenario();
      scenario0.setName("w");
      String string0 = scenario0.getName();
      assertEquals("w", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Scenario scenario0 = new Scenario();
      Scenario.Status scenario_STATUS0 = Scenario.Status.SUCCESS;
      scenario0.setStatus(scenario_STATUS0);
      Scenario.Status scenario_STATUS1 = scenario0.getStatus();
      assertSame(scenario_STATUS1, scenario_STATUS0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Scenario scenario0 = new Scenario();
      boolean boolean0 = scenario0.isFragment();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Scenario scenario0 = new Scenario();
      int int0 = scenario0.getNumStepFailures();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Scenario scenario0 = new Scenario();
      String string0 = scenario0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Scenario scenario0 = new Scenario();
      int int0 = scenario0.getNumStepPasses();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Scenario scenario0 = new Scenario();
      scenario0.setName("");
      String string0 = scenario0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Scenario scenario0 = new Scenario();
      ArrayList<Step> arrayList0 = new ArrayList<Step>();
      scenario0.setSteps(arrayList0);
      ArrayList<Step> arrayList1 = scenario0.getSteps();
      assertEquals(0, arrayList1.size());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Scenario scenario0 = new Scenario();
      ArrayList<Step> arrayList0 = scenario0.getSteps();
      assertNull(arrayList0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Scenario scenario0 = new Scenario();
      scenario0.getStatus();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Scenario scenario0 = new Scenario();
      scenario0.setFragment(true);
      boolean boolean0 = scenario0.isFragment();
      assertTrue(boolean0);
  }
}
