/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 27 13:53:03 CET 2017
 */

package website.automate.manager.api.client.model;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class StepTest{

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Step step0 = new Step();
      Step.Status step_STATUS0 = Step.Status.ERROR;
      step0.setStatus(step_STATUS0);
      assertEquals(Step.Status.ERROR, step0.getStatus());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Step step0 = new Step();
      Step.Status step_STATUS0 = Step.Status.SUCCESS;
      step0.status = step_STATUS0;
      Step.Status step_STATUS1 = step0.getStatus();
      assertEquals(Step.Status.SUCCESS, step_STATUS1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Step step0 = new Step();
      step0.setIndex(1);
      int int0 = step0.getIndex();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Step step0 = new Step();
      step0.setIndex((-1));
      int int0 = step0.getIndex();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Step step0 = new Step();
      step0.getStatus();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Step step0 = new Step();
      int int0 = step0.getIndex();
      assertEquals(0, int0);
  }
}
